// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ErKsA8zzGaOYLCkuJwS3f-8hTU6J-Pk',
    appId: '1:36345677603:web:275c83d03d4387c5e4ee96',
    messagingSenderId: '36345677603',
    projectId: 'seatsync-fdd39',
    authDomain: 'seatsync-fdd39.firebaseapp.com',
    storageBucket: 'seatsync-fdd39.firebasestorage.app',
    measurementId: 'G-4NDYHMR4EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1U2hQUmj2C7bLMOPsPDntYiMDG6kHAOE',
    appId: '1:36345677603:android:0b0b01d62ee126fae4ee96',
    messagingSenderId: '36345677603',
    projectId: 'seatsync-fdd39',
    storageBucket: 'seatsync-fdd39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB87leTS8kSRksFkmAunHgLI1uIJAJ9srE',
    appId: '1:36345677603:ios:fd49e394d0219798e4ee96',
    messagingSenderId: '36345677603',
    projectId: 'seatsync-fdd39',
    storageBucket: 'seatsync-fdd39.firebasestorage.app',
    iosClientId:
        '36345677603-gj03h4hejnpo0nenp0ans92mj2gbs9hh.apps.googleusercontent.com',
    iosBundleId: 'com.example.seatSyncV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB87leTS8kSRksFkmAunHgLI1uIJAJ9srE',
    appId: '1:36345677603:ios:fd49e394d0219798e4ee96',
    messagingSenderId: '36345677603',
    projectId: 'seatsync-fdd39',
    storageBucket: 'seatsync-fdd39.firebasestorage.app',
    iosClientId:
        '36345677603-gj03h4hejnpo0nenp0ans92mj2gbs9hh.apps.googleusercontent.com',
    iosBundleId: 'com.example.seatSyncV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4ErKsA8zzGaOYLCkuJwS3f-8hTU6J-Pk',
    appId: '1:36345677603:web:16203cea8ac749d0e4ee96',
    messagingSenderId: '36345677603',
    projectId: 'seatsync-fdd39',
    authDomain: 'seatsync-fdd39.firebaseapp.com',
    storageBucket: 'seatsync-fdd39.firebasestorage.app',
    measurementId: 'G-PZP317QWBE',
  );
}
